=== brent-hartwig/rsuite-container-template-plugin/doctypes/containerWizardConf/containerWizardConf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.rsicms.com/rsuite/ns/conf/container-wizard" xmlns:c="http://www.rsicms.com/rsuite/ns/conf/container-wizard" xmlns:r="http://www.rsuitecms.com/rsuite/ns/metadata"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
  <xs:import namespace="http://www.rsuitecms.com/rsuite/ns/metadata" schemaLocation="rsuite.xsd"/>
  <xs:element name="container-wizard-conf">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="c:pages"/>
        <xs:element ref="c:primary-container"/>
        <xs:element ref="c:acls"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
      <xs:attribute ref="r:rsuiteId" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="pages">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="c:page"/>
      </xs:sequence>
      <xs:attribute ref="r:rsuiteId" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="page">
    <xs:complexType>
      <xs:attribute name="action-id" use="optional" type="xs:string"/>
      <xs:attribute name="form-id" use="optional" type="xs:string"/>
      <xs:attribute name="api-name" use="optional" type="xs:string"/>
      <xs:attribute name="sub-pages" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="primary-container">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="c:metadata-conf" minOccurs="0"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="c:container-conf"/>
          <xs:element ref="c:xml-mo-conf"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="acl-id" use="required" type="xs:string"/>
      <xs:attribute name="default-acl-id" use="required" type="xs:string"/>
      <xs:attribute ref="r:rsuiteId" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="metadata-conf">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="c:name-value-pair"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name-value-pair">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="container-conf">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="c:metadata-conf" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="acl-id" use="optional" type="xs:string"/>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="xml-mo-conf">
    <xs:complexType>
      <xs:attribute name="acl-id" use="optional" type="xs:string"/>
      <xs:attribute name="required" use="optional" type="xs:boolean"/>
      <xs:attribute name="multiple" use="optional" type="xs:boolean"/>
      <xs:attribute name="name" use="required"/>
      <xs:attribute name="template-lmd-value" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="acls">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="c:acl"/>
      </xs:sequence>
      <xs:attribute ref="r:rsuiteId" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="acl">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="c:ace"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ace">
    <xs:complexType>
      <xs:attribute name="content-permissions" use="required"/>
      <xs:attribute name="project-role" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== brent-hartwig/rsuite-container-template-plugin/src/test/resources/AuditReportProductConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<container-wizard-conf xmlns="http://www.rsicms.com/rsuite/ns/conf/container-wizard" xmlns:r="http://www.rsuitecms.com/rsuite/ns/metadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Audit Report Product Configuration" r:rsuiteId="9927" xsi:schemaLocation="http://www.rsicms.com/rsuite/ns/conf/container-wizard containerWizardConf.xsd">
    
    <pages r:rsuiteId="9929">
        
        <page api-name="gao.newblue.webservice.CreateProductByType" form-id="gao-newblue-form-select-product-type" sub-pages="0"/>
        <page api-name="rsuite-container-wizard-plugin-ws-invoke-wizard" form-id="gao-newblue-form-create-product-page-1" sub-pages="0"/>
        <!--<page form-id="sample.contents.page" sub-pages="0"/>-->
        <page action-id="rsuite-container-wizard-plugin:wizardPage" api-name="rsuite-container-wizard-plugin-ws-invoke-wizard" sub-pages="1"/>
        <page api-name="rsuite-container-wizard-plugin-ws-invoke-wizard" form-id="gao-newblue-form-create-product-page-3" sub-pages="0"/>
        
    </pages>
    
    <primary-container acl-id="non-feedback-containers" default-acl-id="master-sections" r:rsuiteId="9930" type="product">
        
        <container-conf acl-id="feedback-container" name="Reviewer Feedback" type="feedback"/>
        
        <xml-mo-conf multiple="0" name="Cover" required="1" template-lmd-value="AuditReportCover"/>
        <xml-mo-conf multiple="0" name="Abbreviations" required="0" template-lmd-value="AuditReportAbbreviations"/>
        <xml-mo-conf multiple="0" name="Introduction" required="1" template-lmd-value="AuditReportIntroduction"/>
        <xml-mo-conf multiple="0" name="Background" required="1" template-lmd-value="AuditReportBackground"/>
        <xml-mo-conf multiple="1" name="Finding" required="1" template-lmd-value="AuditReportFinding"/>
        <xml-mo-conf multiple="0" name="Conclusions" required="0" template-lmd-value="AuditReportConclusions"/>
        <xml-mo-conf multiple="0" name="Recommendations" required="0" template-lmd-value="AuditReportRecommendations"/>
        <xml-mo-conf multiple="1" name="Agency Comments" required="1" template-lmd-value="AuditReportAgencyComments"/>
        <xml-mo-conf multiple="0" name="Closing" required="0" template-lmd-value="AuditReportClosing"/>
        <xml-mo-conf multiple="1" name="Appendix" required="0" template-lmd-value="AuditReportAppendix"/>
        <!--<xml-mo-conf name="Related Product" template-lmd-value="AuditReportRelatedProduct" required="0" multiple="1"/>-->
        
        <container-conf acl-id="non-feedback-containers" name="images" type="folder"/>
        
    </primary-container>
    
    <acls r:rsuiteId="9931">
        <acl id="non-feedback-containers">
            <ace content-permissions="list, view, edit" project-role="Authors"/>
            <ace content-permissions="list, view" project-role="Reviewers"/>
            <ace content-permissions="list, view" project-role="Referencers"/>
        </acl>
        <acl id="feedback-container">
            <ace content-permissions="list, view" project-role="Authors"/>
            <ace content-permissions="list, view, edit" project-role="Reviewers"/>
            <ace content-permissions="" project-role="Referencers"/>
        </acl>
        <acl id="master-sections">
            <ace content-permissions="list, view, edit, delete" project-role="Authors"/>
            <ace content-permissions="list, view" project-role="Reviewers"/>
            <ace content-permissions="list, view" project-role="Referencers"/>
        </acl>
    </acls>
    
</container-wizard-conf>

=== brent-hartwig/rsuite-container-template-plugin/src/test-disabled/resources/SampleContainerWizardConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<container-wizard-conf 
    xmlns="http://www.rsicms.com/rsuite/ns/conf/container-wizard" 
    xmlns:r="http://www.rsuitecms.com/rsuite/ns/metadata" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.rsicms.com/rsuite/ns/conf/container-wizard containerWizardConf.xsd"
    name="Sample Container Wizard Configuration">
    
    <pages>
        
        <page form-id="acme-form-create-product-page-1" sub-pages="0"/>
        <page action-id="rsuite-container-wizard-plugin:wizardPage" sub-pages="1"/>
        <page form-id="acme-form-create-product-page-3" sub-pages="0"/>
        
    </pages>
    
    <primary-container type="publication" acl-id="non-support-containers" default-acl-id="mo">
        
        <metadata-conf>
            <name-value-pair name="Hello" value="World"/>
            <name-value-pair name="Status" value="New"/>
        </metadata-conf>

        <xml-mo-conf display-name="Cover Page" local-name="cover_page" template-lmd-value="DitaCoverPage" required="1" multiple="0"/>
        <xml-mo-conf display-name="Introduction" local-name="intro" template-lmd-value="DitaIntroduction" required="1" multiple="0"/>
        <xml-mo-conf display-name="Background" local-name="background" template-lmd-value="DitaBackground" required="1" multiple="0"/>
        <xml-mo-conf display-name="Discovery" local-name="discovery" template-lmd-value="DitaDiscovery" required="1" multiple="1"/>
        <xml-mo-conf display-name="Conclusions" local-name="conclusions" template-lmd-value="DitaConclusions" required="0" multiple="0"/>
        <xml-mo-conf display-name="Supplementary" local-name="supplementary" template-lmd-value="DitaSupplementary" required="0" multiple="1"/>
        
        <container-conf type="support" display-name="Supporting Documentation" acl-id="support-container"/>
        <container-conf type="folder" display-name="Images" acl-id="non-support-containers"/>
        
    </primary-container>
    
    <acls>
        <acl id="non-support-containers">
            <ace project-role="SMEs" content-permissions="list, view, edit"/>
            <ace project-role="Reviewers" content-permissions="list, view"/>
            <ace project-role="Managers" content-permissions="list, view, edit, delete"/>
        </acl>
        <acl id="support-container">
            <ace project-role="SMEs" content-permissions="list, view, edit"/>
            <ace project-role="Reviewers" content-permissions="list, view, edit"/>
            <ace project-role="Managers" content-permissions="list, view, edit, delete"/>
        </acl>
        <acl id="mo">
            <ace project-role="SMEs" content-permissions="list, view, edit, delete"/>
            <ace project-role="Reviewers" content-permissions="list, view, edit"/>
            <ace project-role="Managers" content-permissions="list, view, edit, delete"/>
        </acl>
    </acls>
    
</container-wizard-conf>

=== brent-hartwig/rsuite-container-template-plugin/src/test/resources/SampleContainerWizardConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<container-wizard-conf 
    xmlns="http://www.rsicms.com/rsuite/ns/conf/container-wizard" 
    xmlns:r="http://www.rsuitecms.com/rsuite/ns/metadata" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.rsicms.com/rsuite/ns/conf/container-wizard containerWizardConf.xsd"
    name="Sample Container Wizard Configuration">
    
    <pages>
        
        <page form-id="gao-newblue-form-select-product-type" sub-pages="0" api-name="gao.newblue.webservice.CreateProductByType"/>
        <page form-id="gao-newblue-form-create-product-page-1" sub-pages="0" api-name="rsuite-container-wizard-plugin-ws-invoke-wizard"/>
        <!--<page form-id="sample.contents.page" sub-pages="0"/>-->
        <page action-id="rsuite-container-wizard-plugin:wizardPage" sub-pages="1" api-name="rsuite-container-wizard-plugin-ws-invoke-wizard"/>
        <page form-id="gao-newblue-form-create-product-page-3" sub-pages="0" api-name="rsuite-container-wizard-plugin-ws-invoke-wizard"/>
        
    </pages>
    
    <primary-container type="product" acl-id="non-feedback-containers" default-acl-id="master-sections">
        
        <container-conf type="feedback" name="Reviewer Feedback" acl-id="feedback-container"/>
        
        <xml-mo-conf name="Cover" template-lmd-value="SampleCover" required="1" multiple="0"/>
        <xml-mo-conf name="Abbreviations" template-lmd-value="SampleAbbreviations" required="0" multiple="0"/>
        <xml-mo-conf name="Introduction" template-lmd-value="SampleIntroduction" required="1" multiple="0"/>
        <xml-mo-conf name="Background" template-lmd-value="SampleBackground" required="1" multiple="0"/>
        <xml-mo-conf name="Finding" template-lmd-value="SampleFinding" required="1" multiple="1"/>
        <xml-mo-conf name="Conclusions" template-lmd-value="SampleConclusions" required="0" multiple="0"/>
        <xml-mo-conf name="Recommendations" template-lmd-value="SampleRecommendations" required="0" multiple="0"/>
        <xml-mo-conf name="Comments" template-lmd-value="SampleAgencyComments" required="1" multiple="1"/>
        <xml-mo-conf name="Closing" template-lmd-value="SampleClosing" required="0" multiple="0"/>
        <xml-mo-conf name="Appendix" template-lmd-value="SampleAppendix" required="0" multiple="1"/>
        <!--<xml-mo-conf name="Related Product" template-lmd-value="SampleRelatedProduct" required="0" multiple="1"/>-->
        
        <container-conf type="folder" name="images" acl-id="non-feedback-containers"/>
        
    </primary-container>
    
    <acls>
        <acl id="non-feedback-containers">
            <ace project-role="Authors" content-permissions="list, view, edit"/>
            <ace project-role="Reviewers" content-permissions="list, view"/>
            <ace project-role="Referencers" content-permissions="list, view"/>
        </acl>
        <acl id="feedback-container">
            <ace project-role="Authors" content-permissions="list, view"/>
            <ace project-role="Reviewers" content-permissions="list, view, edit"/>
            <ace project-role="Referencers" content-permissions=""/>
        </acl>
        <acl id="master-sections">
            <ace project-role="Authors" content-permissions="list, view, edit, delete"/>
            <ace project-role="Reviewers" content-permissions="list, view"/>
            <ace project-role="Referencers" content-permissions="list, view"/>
        </acl>
    </acls>
    
</container-wizard-conf>
